### ISSUE TITLE
Release to CPAN

### ISSUE THREAD

**Issue by reneeb** [yko/mojolicious-plugin-linkedcontent#3]
Hi,

can you release a new version to CPAN? Github has a fix where ```render( partial => 1 )``` was replaced with ```render_to_string()```.

Kind regards,
Renee

**Comment by reneeb** [comment]
```render_to_string``` was added in Mojolicious 5.0 to replace the ```render( partial => 1 )```. So the minimum required version of Mojolicious has to be 5.0.

**Comment by oliverguenther** [comment]
Hi, thanks for the reminder. I've just pushed the latest changes as v0.07 to CPAN:

https://metacpan.org/release/OLG/Mojolicious-Plugin-LinkedContent-0.07

**Comment by reneeb** [comment]
Thanks, now everything for your module is green: http://mojo.perl-services.de/
